name: ptlflow
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python>=3.8,<=3.10
  - pip
  - cudatoolkit>=11.0,<=11.6
  - pytorch>=1.8.1,<=1.12
  - pytorch-lightning>=1.1.0,<=1.6,!=1.3,!=1.4
  - torchmetrics>=0.2,<=0.9
  - torchvision>=0.8.2,<=0.13
  - pip:
    - einops>=0.3.0,<=0.4.*
    - numpy>=1.17.0,<=1.22.*
    - opencv-python>=4.0.0.21,<=4.6.*
    - packaging>=20.0,<=21.*
    - pandas>=1.1.0,<=1.4.*
    - pillow>=5.0,<=9.2.*
    - plotly>=5.0.0,<=5.9.*
    - pypng~=0.0.16
    - requests>=2.0.0,<=2.28.*
    - scipy>=1.0.0,<=1.9.*
    - tabulate~=0.8.3
    - timm~=0.6.3
    - tqdm>=4.41.0,<=4.64.*