"""
Estimate optical flow on standard test datasets.

Use this script to generate the predictions to be submitted to the benchmark website.

Note that this script will only generate the flow files in the format specified by the respective benchmark. However,
additional steps may be necessary before submitting. For example, for the MPI-Sintel benchmark you need to download and run the
official bundler on the results generated by this script.
"""

# =============================================================================
# Copyright 2021 Henrique Morimitsu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# =============================================================================

import logging
import sys
from argparse import ArgumentParser, Namespace
from pathlib import Path
from typing import Any, Dict, Optional

import cv2 as cv
import numpy as np
import torch
from torch.utils.data import DataLoader
from tqdm import tqdm

from ptlflow import get_model, get_model_reference
from ptlflow.models.base_model.base_model import BaseModel
from ptlflow.utils import flow_utils
from ptlflow.utils.io_adapter import IOAdapter
from ptlflow.utils.utils import (
    add_datasets_to_parser, config_logging, get_list_of_available_models_list, tensor_dict_to_numpy)

config_logging()


def _init_parser() -> ArgumentParser:
    parser = ArgumentParser()
    parser.add_argument(
        'model', type=str, choices=get_list_of_available_models_list(),
        help='Name of the model to use.')
    parser.add_argument(
        '--output_path', type=str, default=str(Path('outputs/test')),
        help='Path to the directory where the validation results will be saved.')
    parser.add_argument(
        '--show', action='store_true',
        help='If set, the results are shown on the screen.')
    parser.add_argument(
        '--max_forward_side', type=int, default=None,
        help=('If max(height, width) of the input image is larger than this value, then the image is downscaled '
              'before the forward and the outputs are bilinearly upscaled to the original resolution.'))
    parser.add_argument(
        '--max_show_side', type=int, default=1000,
        help=('If max(height, width) of the output image is larger than this value, then the image is downscaled '
              'before showing it on the screen.'))
    return parser


def generate_outputs(
    args: Namespace,
    inputs: Dict[str, torch.Tensor],
    preds: Dict[str, torch.Tensor],
    dataloader_name: str,
    batch_idx: int,
    metadata: Optional[Dict[str, Any]] = None
) -> None:
    """Display on screen and/or save outputs to disk, if required.

    Parameters
    ----------
    args : Namespace
        The arguments with the required values to manage the outputs.
    inputs : Dict[str, torch.Tensor]
        The inputs loaded from the dataset (images, groundtruth).
    preds : Dict[str, torch.Tensor]
        The model predictions (optical flow and others).
    dataloader_name : str
        A string to identify from which dataloader these inputs came from.
    batch_idx : int
        Indicates in which position of the loader this input is.
    metadata : Dict[str, Any], optional
        Metadata about this input, if available.
    """
    inputs = tensor_dict_to_numpy(inputs)
    preds = tensor_dict_to_numpy(preds)
    preds['flows_viz'] = flow_utils.flow_to_rgb(preds['flows'])[:, :, ::-1]
    if preds.get('flows_b') is not None:
        preds['flows_b_viz'] = flow_utils.flow_to_rgb(preds['flows_b'])[:, :, ::-1]

    _write_to_file(args, preds, dataloader_name, batch_idx, metadata)

    if args.show:
        _show(inputs, preds, args.max_show_side)


def test(
    args: Namespace,
    model: BaseModel
) -> None:
    """Run predictions on the test dataset.

    Parameters
    ----------
    args : Namespace
        Arguments to configure the model and the test.
    model : BaseModel
        The model to be used for testing.

    See Also
    --------
    ptlflow.models.base_model.base_model.BaseModel : The parent class of the available models.
    """
    model.eval()
    if torch.cuda.is_available():
        model = model.cuda()

    dataloaders = model.test_dataloader()
    dataloaders = {model.test_dataloader_names[i]: dataloaders[i] for i in range(len(dataloaders))}

    for dataset_name, dl in dataloaders.items():
        test_one_dataloader(args, model, dl, dataset_name)


@torch.no_grad()
def test_one_dataloader(
    args: Namespace,
    model: BaseModel,
    dataloader: DataLoader,
    dataloader_name: str,
) -> None:
    """Perform predictions for all examples of one test dataloader.

    Parameters
    ----------
    args : Namespace
        Arguments to configure the model and the validation.
    model : BaseModel
        The model to be used for validation.
    dataloader : DataLoader
        The dataloader for the validation.
    dataloader_name : str
        A string to identify this dataloader.
    """
    for i, inputs in enumerate(tqdm(dataloader)):
        scale_factor = (
            None if args.max_forward_side is None else float(args.max_forward_side) / min(inputs['images'].shape[-2:]))

        io_adapter = IOAdapter(
            model, inputs['images'].shape[-2:], target_scale_factor=scale_factor, cuda=torch.cuda.is_available())
        inputs = io_adapter.prepare_inputs(inputs=inputs)

        preds = model(inputs)

        inputs = io_adapter.unpad_and_unscale(inputs)
        preds = io_adapter.unpad_and_unscale(preds)

        generate_outputs(args, inputs, preds, dataloader_name, i, inputs.get('meta'))


def _show(
    inputs: Dict[str, np.ndarray],
    preds: Dict[str, np.ndarray],
    max_show_side: int
) -> None:
    for k, v in inputs.items():
        if isinstance(v, np.ndarray) and (len(v.shape) == 2 or v.shape[2] == 1 or v.shape[2] == 3):
            if max(v.shape[:2]) > max_show_side:
                scale_factor = float(max_show_side) / max(v.shape[:2])
                v = cv.resize(v, (int(scale_factor*v.shape[1]), int(scale_factor*v.shape[0])))
            cv.imshow(k, v)
    for k, v in preds.items():
        if isinstance(v, np.ndarray) and (len(v.shape) == 2 or v.shape[2] == 1 or v.shape[2] == 3):
            if max(v.shape[:2]) > max_show_side:
                scale_factor = float(max_show_side) / max(v.shape[:2])
                v = cv.resize(v, (int(scale_factor*v.shape[1]), int(scale_factor*v.shape[0])))
            cv.imshow('pred_'+k, v)
    cv.waitKey(1)


def _write_to_file(
    args: Namespace,
    preds: Dict[str, np.ndarray],
    dataloader_name: str,
    batch_idx: int,
    metadata: Optional[Dict[str, Any]] = None
) -> None:
    out_root_dir = Path(args.output_path)
    dataloader_tokens = dataloader_name.split('-')
    if dataloader_tokens[0] == 'kitti':
        out_root_dir /= f'{dataloader_tokens[0]}{dataloader_tokens[1]}'
        flow_ext = 'png'
    elif dataloader_tokens[0] == 'sintel':
        out_root_dir = out_root_dir / dataloader_tokens[0] / dataloader_tokens[1]
        flow_ext = 'flo'

    extra_dirs = ''
    if metadata is not None:
        img_path = Path(metadata['image_paths'][0][0])
        image_name = img_path.stem
        if 'sintel' in dataloader_name:
            seq_name = img_path.parts[-2]
            extra_dirs = seq_name
    else:
        image_name = f'{batch_idx:08d}'

    out_dir = out_root_dir / extra_dirs
    out_dir.mkdir(parents=True, exist_ok=True)
    flow_utils.flow_write(out_dir / f'{image_name}.{flow_ext}', preds['flows'])


if __name__ == '__main__':
    parser = _init_parser()

    # TODO: It is ugly that the model has to be gotten from the argv rather than the argparser.
    # However, I do not see another way, since the argparser requires the model to load some of the args.
    FlowModel = None
    if len(sys.argv) > 1 and sys.argv[1] not in ['-h', '--help']:
        FlowModel = get_model_reference(sys.argv[1])
        parser = FlowModel.add_model_specific_args(parser)

    add_datasets_to_parser(parser, 'datasets.yml')

    args = parser.parse_args()

    logging.info('The outputs will be saved to %s.', args.output_path)

    model_id = args.model
    if args.pretrained_ckpt is not None:
        model_id += f'_{args.pretrained_ckpt}'
    args.output_path = Path(args.output_path) / model_id
    model = get_model(sys.argv[1], args.pretrained_ckpt, args)
    args.output_path.mkdir(parents=True, exist_ok=True)

    metrics_df = test(args, model)
