# This workflow will install Python dependencies, run tests with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pytorch-lightning

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pytorch-lightning: [1.1.8, 1.2.10, 1.5.10, 1.6.5]

    steps:
      - uses: actions/checkout@v3
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Replace pytorch-lightning
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "pytorch-lightning>=1.1.0,<=1.6"
          replace: "pytorch-lightning==${{ matrix.pytorch-lightning }}"
          regex: false
          include: "environment.yml"
      - name: Install dependencies
        run: |
          conda env update --file environment.yml --name base
          python -m pip install --upgrade pip setuptools==59.5.0 wheel
          python -m pip install --upgrade pytest
      - name: Test with pytest
        run: |
          python -m pytest
